### ISSUE TITLE
Repeated core dumps

### ISSUE THREAD

**Issue by kakra** [ValveSoftware/Fossilize#211]
```
# coredumpctl debug 21783
           PID: 21783 (fossilize_repla)
           UID: 500 (kakra)
           GID: 500 (kakra)
        Signal: 11 (SEGV)
     Timestamp: Thu 2023-01-12 18:08:39 CET (18h ago)
  Command Line: /home/kakra/.local/share/Steam/ubuntu12_32/../ubuntu12_64/fossilize_replay /mnt/xfs-storage/kakra/shadercache/8870/fozpipelinesv6/steamapprun_pipeline_cache.904f69d2b1b44b65/steamapp_pipeline_cache.foz /mnt/xfs-storage/kakra/shadercache/8870/fozpipelinesv6/steamapprun_pipeline_cache.904f69d2b1b44b65/steam_pipeline_cache.foz --master-process --quiet-slave --shmem-fd 141 --control-fd 160 --spirv-val --num-threads 5 --on-disk-validation-whitelist /mnt/xfs-storage/kakra/shadercache/8870/fozpipelinesv6/steamapprun_pipeline_cache.904f69d2b1b44b65/steam_pipeline_cache_whitelist --replayer-cache /mnt/xfs-storage/kakra/shadercache/8870/fozpipelinesv6/steamapprun_pipeline_cache.904f69d2b1b44b65/replay_cache --device-index 0 --timeout-seconds 10 --implicit-whitelist 0
    Executable: /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay
 Control Group: /user.slice/user-500.slice/user@500.service/app.slice/app-steam-dc690f3983d14de3ae92987b8033b778.scope
          Unit: user@500.service
     User Unit: app-steam-dc690f3983d14de3ae92987b8033b778.scope
         Slice: user-500.slice
     Owner UID: 500 (kakra)
       Boot ID: 99d3c1cb2f59441bb087e7dae3738fb6
    Machine ID: 121b87ca633e8ac0016656680000001b
      Hostname: jupiter
       Storage: /var/lib/systemd/coredump/core.fossilize_repla.500.99d3c1cb2f59441bb087e7dae3738fb6.21783.1673543319000000.zst (present)
  Size on Disk: 74.3M
       Message: Process 21783 (fossilize_repla) of user 500 dumped core.

                Module libVkLayer_MESA_device_select.so without build-id.
                Module libxcb-glx.so.0 without build-id.
                Module libXext.so.6 without build-id.
                Module libX11.so.6 without build-id.
                Module libmd.so.0 without build-id.
                Module libbsd.so.0 without build-id.
                Module libXdmcp.so.6 without build-id.
                Module libXau.so.6 without build-id.
                Module libgcc_s.so.1 without build-id.
                Module libffi.so.8 without build-id.
                Module libstdc++.so.6 without build-id.
                Module libxshmfence.so.1 without build-id.
                Module libxcb-shm.so.0 without build-id.
                Module libxcb-randr.so.0 without build-id.
                Module libxcb-sync.so.1 without build-id.
                Module libxcb-xfixes.so.0 without build-id.
                Module libxcb-present.so.0 without build-id.
                Module libX11-xcb.so.1 without build-id.
                Module libxcb.so.1 without build-id.
                Module libunwind.so.8 without build-id.
                Module libzstd.so.1 without build-id.
                Module libexpat.so.1 without build-id.
                Module libudev.so.1 without build-id.
                Module libz.so.1 without build-id.
                Module libwayland-client.so.0 without build-id.
                Module libxcb-dri3.so.0 without build-id.
                Module libdrm.so.2 without build-id.
                Module libm.so.6 without build-id.
                Module libvulkan.so.1 without build-id.
                Module ld-linux-x86-64.so.2 without build-id.
                Module libc.so.6 without build-id.
                Module libpthread.so.0 without build-id.
                Module librt.so.1 without build-id.
                Module libdl.so.2 without build-id.
                Stack trace of thread 21783:
                #0  0x0000560393a1f14e n/a (/home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay + 0x6814e)
                ELF object binary architecture: AMD x86-64

GNU gdb (Gentoo 12.1 vanilla) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay...
(No debugging symbols found in /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay)

warning: Can't open file /dev/shm/fossilize-replayer-21615-0 (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/fossilize-external-3909967-8 (deleted) during file-backed mapping note processing

warning: core file may not match specified executable file.
[New LWP 21783]
[New LWP 21799]
[New LWP 21792]
[New LWP 21790]
[New LWP 21794]
[New LWP 21793]
[New LWP 21797]
[New LWP 21795]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Core was generated by `/home/kakra/.local/share/Steam/ubuntu12_32/../ubuntu12_64/fossilize_replay /mnt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000560393a1f14e in _start ()
[Current thread is 1 (Thread 0x7f0c27efb780 (LWP 21783))]
(gdb) thread apply all bt full

Thread 8 (Thread 0x7f0c153f46c0 (LWP 21795)):
#0  0x00007f0c27ff0bcf in __GI___poll (fds=0x56039a1dfb90, nfds=3, timeout=100) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f0c1de91f39 in ?? () from /usr/lib64/libcuda.so.1
No symbol table info available.
#2  0x00007f0c1df46014 in ?? () from /usr/lib64/libcuda.so.1
No symbol table info available.
#3  0x00007f0c1de948b8 in ?? () from /usr/lib64/libcuda.so.1
No symbol table info available.
#4  0x00007f0c27f7f802 in start_thread (arg=<optimized out>) at pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140733106809008, 5509516906133591195, 139689872803520, 2, 139690186896768, 139689864413184, -5589646562614963045, -5589543828881795941}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#5  0x00007f0c27ffe3ec in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 7 (Thread 0x7f0c127926c0 (LWP 21797)):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x7f0c12791d30, op=393, expected=0, futex_word=0x7f0bdc000d48) at futex-internal.c:57
        sc_cancel_oldtype = 0
        __arg6 = <optimized out>
        __arg3 = <optimized out>
        _a5 = <optimized out>
        _a2 = <optimized out>
        sc_ret = <optimized out>
        __arg4 = <optimized out>
        __arg1 = <optimized out>
        _a6 = <optimized out>
        _a3 = <optimized out>
        resultvar = <optimized out>
        __arg5 = <optimized out>
        __arg2 = <optimized out>
        _a4 = <optimized out>
        _a1 = <optimized out>
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7f0bdc000d48, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f0c12791d30, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
        err = <optimized out>
        clockbit = 256
        op = 393
#2  0x00007f0c27f7c4ab in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7f0bdc000d48, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f0c12791d30, private=pri--Type <RET> for more, q to quit, c to continue without paging--c
vate@entry=0) at futex-internal.c:139
No locals.
#3  0x00007f0c27f7eef4 in __pthread_cond_wait_common (abstime=0x7f0c12791d30, clockid=0, mutex=0x560396c126e0, cond=0x7f0bdc000d20) at pthread_cond_wait.c:503
        spin = 0
        buffer = {__routine = 0x7f0c27f7e960 <__condvar_cleanup_waiting>, __arg = 0x7f0c12791cc0, __canceltype = -1770092744, __prev = 0x0}
        cbuffer = {wseq = 2368, cond = 0x7f0bdc000d20, mutex = 0x560396c126e0, private = 0}
        err = <optimized out>
        g = 0
        flags = <optimized out>
        g1_start = <optimized out>
        maxspin = 0
        signals = <optimized out>
        result = 0
        wseq = 2368
        seq = 1184
        private = 0
        maxspin = <optimized out>
        err = <optimized out>
        result = <optimized out>
        wseq = <optimized out>
        g = <optimized out>
        seq = <optimized out>
        flags = <optimized out>
        private = <optimized out>
        signals = <optimized out>
        done = <optimized out>
        g1_start = <optimized out>
        spin = <optimized out>
        buffer = <optimized out>
        cbuffer = <optimized out>
        s = <optimized out>
#4  ___pthread_cond_timedwait64 (cond=0x7f0bdc000d20, mutex=0x560396c126e0, abstime=0x7f0c12791d30) at pthread_cond_wait.c:643
        flags = <optimized out>
        clockid = 0
#5  0x00007f0c22a6c820 in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#6  0x00007f0c22f441ce in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#7  0x00007f0c22f3cddd in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#8  0x00007f0c22a6f7da in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#9  0x00007f0c27f7f802 in start_thread (arg=<optimized out>) at pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140733106810576, 5509516906133591195, 139689826264768, 2, 139690186896768, 139689817874432, -5589643761222544229, -5589543828881795941}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#10 0x00007f0c27ffe3ec in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 6 (Thread 0x7f0c1699c6c0 (LWP 21793)):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x7f0c1699be00, op=393, expected=0, futex_word=0x7f0bec000d48) at futex-internal.c:57
        sc_cancel_oldtype = 0
        __arg6 = <optimized out>
        __arg3 = <optimized out>
        _a5 = <optimized out>
        _a2 = <optimized out>
        sc_ret = <optimized out>
        __arg4 = <optimized out>
        __arg1 = <optimized out>
        _a6 = <optimized out>
        _a3 = <optimized out>
        resultvar = <optimized out>
        __arg5 = <optimized out>
        __arg2 = <optimized out>
        _a4 = <optimized out>
        _a1 = <optimized out>
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7f0bec000d48, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f0c1699be00, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
        err = <optimized out>
        clockbit = 256
        op = 393
#2  0x00007f0c27f7c4ab in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7f0bec000d48, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f0c1699be00, private=private@entry=0) at futex-internal.c:139
No locals.
#3  0x00007f0c27f7eef4 in __pthread_cond_wait_common (abstime=0x7f0c1699be00, clockid=0, mutex=0x560397f9f2c0, cond=0x7f0bec000d20) at pthread_cond_wait.c:503
        spin = 0
        buffer = {__routine = 0x7f0c27f7e960 <__condvar_cleanup_waiting>, __arg = 0x7f0c1699bd90, __canceltype = 370786304, __prev = 0x0}
        cbuffer = {wseq = 240, cond = 0x7f0bec000d20, mutex = 0x560397f9f2c0, private = 0}
        err = <optimized out>
        g = 0
        flags = <optimized out>
        g1_start = <optimized out>
        maxspin = 0
        signals = <optimized out>
        result = 0
        wseq = 240
        seq = 120
        private = 0
        maxspin = <optimized out>
        err = <optimized out>
        result = <optimized out>
        wseq = <optimized out>
        g = <optimized out>
        seq = <optimized out>
        flags = <optimized out>
        private = <optimized out>
        signals = <optimized out>
        done = <optimized out>
        g1_start = <optimized out>
        spin = <optimized out>
        buffer = <optimized out>
        cbuffer = <optimized out>
        s = <optimized out>
#4  ___pthread_cond_timedwait64 (cond=0x7f0bec000d20, mutex=0x560397f9f2c0, abstime=0x7f0c1699be00) at pthread_cond_wait.c:643
        flags = <optimized out>
        clockid = 0
#5  0x00007f0c22a6c820 in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#6  0x00007f0c22eb667d in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#7  0x00007f0c22a6f7da in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#8  0x00007f0c27f7f802 in start_thread (arg=<optimized out>) at pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140733106811280, 5509516906133591195, 139689895511744, 2, 139690186896768, 139689887121408, -5589651738050554725, -5589543828881795941}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#9  0x00007f0c27ffe3ec in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 5 (Thread 0x7f0c1619b6c0 (LWP 21794)):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7f0be4000d48) at futex-internal.c:57
        sc_cancel_oldtype = 0
        __arg6 = <optimized out>
        __arg3 = <optimized out>
        _a5 = <optimized out>
        _a2 = <optimized out>
        sc_ret = <optimized out>
        __arg4 = <optimized out>
        __arg1 = <optimized out>
        _a6 = <optimized out>
        _a3 = <optimized out>
        resultvar = <optimized out>
        __arg5 = <optimized out>
        __arg2 = <optimized out>
        _a4 = <optimized out>
        _a1 = <optimized out>
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7f0be4000d48, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
        err = <optimized out>
        clockbit = 256
        op = 393
#2  0x00007f0c27f7c4ab in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7f0be4000d48, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
No locals.
#3  0x00007f0c27f7ebf0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5603980b6e30, cond=0x7f0be4000d20) at pthread_cond_wait.c:503
        spin = 0
        buffer = {__routine = 0x7f0c27f7e960 <__condvar_cleanup_waiting>, __arg = 0x7f0c1619ad80, __canceltype = -469762000, __prev = 0x0}
        cbuffer = {wseq = 0, cond = 0x7f0be4000d20, mutex = 0x5603980b6e30, private = 0}
        err = <optimized out>
        g = 0
        flags = <optimized out>
        g1_start = <optimized out>
        maxspin = 0
        signals = <optimized out>
        result = 0
        wseq = 0
        seq = 0
        private = 0
        maxspin = <optimized out>
        err = <optimized out>
        result = <optimized out>
        wseq = <optimized out>
        g = <optimized out>
        seq = <optimized out>
        flags = <optimized out>
        private = <optimized out>
        signals = <optimized out>
        done = <optimized out>
        g1_start = <optimized out>
        spin = <optimized out>
        buffer = <optimized out>
        cbuffer = <optimized out>
        s = <optimized out>
#4  ___pthread_cond_wait (cond=0x7f0be4000d20, mutex=0x5603980b6e30) at pthread_cond_wait.c:618
No locals.
#5  0x00007f0c22a6c7bf in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#6  0x00007f0c22eab070 in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#7  0x00007f0c22a6f7da in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#8  0x00007f0c27f7f802 in start_thread (arg=<optimized out>) at pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140733106811248, 5509516906133591195, 139689887119040, 2, 139690186896768, 139689878728704, -5589652837025311589, -5589543828881795941}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#9  0x00007f0c27ffe3ec in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 4 (Thread 0x7f0c1799e6c0 (LWP 21790)):
#0  0x00007f0c27ff0bcf in __GI___poll (fds=0x5603980b6e70, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f0c1de91f39 in ?? () from /usr/lib64/libcuda.so.1
No symbol table info available.
#2  0x00007f0c1df46014 in ?? () from /usr/lib64/libcuda.so.1
No symbol table info available.
#3  0x00007f0c1de948b8 in ?? () from /usr/lib64/libcuda.so.1
No symbol table info available.
#4  0x00007f0c27f7f802 in start_thread (arg=<optimized out>) at pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140733106810992, 5509516906133591195, 139689912297152, 17, 139690186896768, 139689903906816, -5589649535806073701, -5589543828881795941}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#5  0x00007f0c27ffe3ec in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 3 (Thread 0x7f0c1719d6c0 (LWP 21792)):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x7f0c1719cdb0, op=393, expected=0, futex_word=0x7f0bfc000d48) at futex-internal.c:57
        sc_cancel_oldtype = 0
        __arg6 = <optimized out>
        __arg3 = <optimized out>
        _a5 = <optimized out>
        _a2 = <optimized out>
        sc_ret = <optimized out>
        __arg4 = <optimized out>
        __arg1 = <optimized out>
        _a6 = <optimized out>
        _a3 = <optimized out>
        resultvar = <optimized out>
        __arg5 = <optimized out>
        __arg2 = <optimized out>
        _a4 = <optimized out>
        _a1 = <optimized out>
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7f0bfc000d48, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f0c1719cdb0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
        err = <optimized out>
        clockbit = 256
        op = 393
#2  0x00007f0c27f7c4ab in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7f0bfc000d48, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f0c1719cdb0, private=private@entry=0) at futex-internal.c:139
No locals.
#3  0x00007f0c27f7eef4 in __pthread_cond_wait_common (abstime=0x7f0c1719cdb0, clockid=0, mutex=0x560397fa2d90, cond=0x7f0bfc000d20) at pthread_cond_wait.c:503
        spin = 0
        buffer = {__routine = 0x7f0c27f7e960 <__condvar_cleanup_waiting>, __arg = 0x7f0c1719cd40, __canceltype = 959592758, __prev = 0x0}
        cbuffer = {wseq = 120, cond = 0x7f0bfc000d20, mutex = 0x560397fa2d90, private = 0}
        err = <optimized out>
        g = 0
        flags = <optimized out>
        g1_start = <optimized out>
        maxspin = 0
        signals = <optimized out>
        result = 0
        wseq = 120
        seq = 60
        private = 0
        maxspin = <optimized out>
        err = <optimized out>
        result = <optimized out>
        wseq = <optimized out>
        g = <optimized out>
        seq = <optimized out>
        flags = <optimized out>
        private = <optimized out>
        signals = <optimized out>
        done = <optimized out>
        g1_start = <optimized out>
        spin = <optimized out>
        buffer = <optimized out>
        cbuffer = <optimized out>
        s = <optimized out>
#4  ___pthread_cond_timedwait64 (cond=0x7f0bfc000d20, mutex=0x560397fa2d90, abstime=0x7f0c1719cdb0) at pthread_cond_wait.c:643
        flags = <optimized out>
        clockid = 0
#5  0x00007f0c22a6c820 in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#6  0x00007f0c22e911d2 in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#7  0x00007f0c22a6f7da in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#8  0x00007f0c27f7f802 in start_thread (arg=<optimized out>) at pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140733106811200, 5509516906133591195, 139689903904448, 2, 139690186896768, 139689895514112, -5589650634780830565, -5589543828881795941}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#9  0x00007f0c27ffe3ec in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
No locals.

Thread 2 (Thread 0x7f0c11f916c0 (LWP 21799)):
#0  0x00007f0c22dbb29e in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#1  0x00007f0c22e447d7 in ?? () from /usr/lib64/libnvidia-glcore.so.525.78.01
No symbol table info available.
#2  0x00007f0c2418f424 in ?? () from /home/kakra/.local/share/Steam/ubuntu12_64/steamoverlayvulkanlayer.so
No symbol table info available.
#3  0x00007f0c24193ecf in vkDestroyDevice () from /home/kakra/.local/share/Steam/ubuntu12_64/steamoverlayvulkanlayer.so
No symbol table info available.
#4  0x0000560394b51c30 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (Thread 0x7f0c27efb780 (LWP 21783)):
#0  0x0000560393a1f14e in _start ()
No symbol table info available.
(gdb)
```

I didn't check if it is always the same crash but it's repeating (going back to August 2022):
```
# coredumpctl | fgrep fossilize
[...]
Fri 2023-01-06 22:31:59 CET  4192741 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Fri 2023-01-06 22:34:27 CET  4193721 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Fri 2023-01-06 22:35:26 CET      487 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Fri 2023-01-06 22:36:15 CET      866 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Fri 2023-01-06 22:36:16 CET      863 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Fri 2023-01-06 22:59:47 CET     7791 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Fri 2023-01-06 23:00:35 CET     8399 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Fri 2023-01-06 23:00:36 CET     8397 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Fri 2023-01-06 23:02:06 CET     9014 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 03:39:43 CET    13779 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 03:39:47 CET    13775 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 03:43:19 CET    16516 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 03:43:25 CET    16826 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 03:43:27 CET    16887 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 03:43:28 CET    16852 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 03:43:28 CET    16896 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 06:36:11 CET    66227 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 06:36:14 CET    66247 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 06:36:15 CET    66248 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 06:57:35 CET    73782 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 06:57:46 CET    73818 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 06:58:21 CET    74063 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 06:58:21 CET    74070 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Sat 2023-01-07 06:58:24 CET    74117 500 500 SIGSEGV missing  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                              -
Wed 2023-01-11 10:49:12 CET  3758236 500 500 SIGSEGV present  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                          15.1M
Wed 2023-01-11 10:49:13 CET  3758240 500 500 SIGSEGV present  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                          14.9M
Thu 2023-01-12 18:08:41 CET    21783 500 500 SIGSEGV present  /home/kakra/.local/share/Steam/ubuntu12_64/fossilize_replay                                          74.3M
```

**Comment by kakra** [comment]
See also #117
